[build]
  publish = "."
  command = "bash netlify_build_fix.sh"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  PYTHON_VERSION = "3.9"
  NODE_VERSION = "18"
  ENABLE_SYNONYMS = "true"
  ENABLE_CONTEXT_EXTRACTION = "true"
  CONFIDENCE_THRESHOLD = "0.3"
  MAX_CHUNKS = "3"
  CHUNK_SIZE = "1500"
  CHUNK_OVERLAP = "300"

[functions]
  directory = "functions"
  node_bundler = "esbuild"
  included_files = ["PDFs/**/*"]
  external_node_modules = ["@netlify/functions"]

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS" 