# render.yaml
services:
  - type: web
    name: frontend
    env: docker
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app_friendly.py --server.port=$PORT --server.address=0.0.0.0
    healthCheckPath: /health  # precisaremos de um pequeno endpoint
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false           # encrypted
      - key: ASTRA_DB_TOKEN
        sync: false
      - key: ASTRA_DB_ENDPOINT
        sync: false
