services:
  - type: web
    name: chatbot-dispensacao
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app_production.py"
    runtime: python
