# render.yaml
services:
  - type: web
    env: python
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run streamlit_app_friendly.py --server.port=$PORT --server.address=0.0.0.0
    healthCheckPath: /health  # precisaremos de um pequeno endpoint
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false           # encrypted
      - key: ASTRA_DB_TOKEN
        sync: false
      - key: ASTRA_DB_ENDPOINT
        sync: false
# As variáveis ASTRA_DB_ENDPOINT, ASTRA_DB_TOKEN e OPENROUTER_API_KEYROTEIRO_DISP_KIMIE_K2FREE são configuradas via secrets/env do Render ou Codespace
